apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kafka-producer-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "kafka-producer-chart.name" . }}
      commit: {{ .Values.environment.commitId }}
  template:
    metadata:
      labels:
        app: {{ template "kafka-producer-chart.name" . }}
        commit: {{ .Values.environment.commitId }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Chart.Name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8585