apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka-producer-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ template "kafka-producer-chart.name" . }}